# Generated by Django 4.2.3 on 2023-07-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("irrigation_frequency", models.IntegerField()),
                ("crop", models.ManyToManyField(to="schedules.crop")),
                (
                    "irrigation_method",
                    models.ManyToManyField(to="schedules.irrigationmethod"),
                ),
                ("soil_type", models.ManyToManyField(to="schedules.soiltype")),
            ],
        ),
    ]
