# Generated by Django 4.2.3 on 2023-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_farmer"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrrigationTimeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pump_capacity", models.FloatField()),
                ("time_required", models.FloatField()),
                (
                    "irrigation_method",
                    models.ManyToManyField(to="schedules.irrigationmethod"),
                ),
                ("soil_type", models.ManyToManyField(to="schedules.soiltype")),
            ],
        ),
        migrations.CreateModel(
            name="FarmerCropRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.FloatField()),
                ("irrigation_frequency", models.IntegerField()),
                ("crop", models.ManyToManyField(to="schedules.crop")),
                ("farmer", models.ManyToManyField(to="schedules.farmer")),
                (
                    "irrigation_method",
                    models.ManyToManyField(to="schedules.irrigationmethod"),
                ),
                ("soil_type", models.ManyToManyField(to="schedules.soiltype")),
            ],
        ),
    ]
