# Generated by Django 4.2.3 on 2023-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_irrigationtimerate_farmercroprelation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerPowerRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("number_of_days", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
