# Generated by Django 4.2.3 on 2023-07-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_farmerpowerrequirement_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayNightSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "supply_period",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("night", "Night"),
                            ("afternoon", "Afternoon"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.schedule",
                    ),
                ),
            ],
        ),
    ]
