# Generated by Django 4.2.3 on 2023-07-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0007_farmerpowerrequirement_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmerpowerrequirement",
            old_name="is_night_irrigation",
            new_name="is_night_irrigation_acceptable",
        ),
        migrations.RemoveField(
            model_name="farmercroprelation",
            name="irrigation_frequency",
        ),
        migrations.RemoveField(
            model_name="farmerpowerrequirement",
            name="irrigation_pump",
        ),
        migrations.AddField(
            model_name="farmerpowerrequirement",
            name="delta_period_between_irrigation",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="farmerpowerrequirement",
            name="farmer_pump",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pump_for_irrigation",
                to="schedules.farmerpumprelation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmerpowerrequirement",
            name="number_of_irrigation",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmerpowerrequirement",
            name="transfer_source_pump",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pump_for_transfer",
                to="schedules.farmerpumprelation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmerpumprelation",
            name="dt_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="duration_of_supply",
            field=models.FloatField(default=8.0),
        ),
    ]
