# Generated by Django 4.2.3 on 2023-07-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "schedules",
            "0008_rename_is_night_irrigation_farmerpowerrequirement_is_night_irrigation_acceptable_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerpowerrequirement",
            name="transfer_source_pump",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pump_for_transfer",
                to="schedules.farmerpumprelation",
            ),
        ),
    ]
