# Generated by Django 4.2.3 on 2023-07-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0010_alter_farmerpowerrequirement_transfer_slot_duriation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="irrigationtimerate",
            name="irrigation_method",
        ),
        migrations.RemoveField(
            model_name="irrigationtimerate",
            name="soil_type",
        ),
        migrations.AlterModelTable(
            name="croprelation",
            table="crop_relations",
        ),
        migrations.AlterModelTable(
            name="daynightschedule",
            table="day_night_schedules",
        ),
        migrations.AlterModelTable(
            name="farmer",
            table="farmers",
        ),
        migrations.AlterModelTable(
            name="farmercroprelation",
            table="farmer_crops",
        ),
        migrations.AlterModelTable(
            name="farmerpowerrequirement",
            table="farmer_power_requirements",
        ),
        migrations.AlterModelTable(
            name="farmerpumprelation",
            table="farmer_pummps",
        ),
        migrations.AlterModelTable(
            name="irrigationmethod",
            table="irrigation_methods",
        ),
        migrations.AlterModelTable(
            name="irrigationtimerate",
            table="irrigation_time_rates",
        ),
        migrations.AlterModelTable(
            name="schedule",
            table="schedules",
        ),
        migrations.AlterModelTable(
            name="soiltype",
            table="soil_types",
        ),
        migrations.AddField(
            model_name="irrigationtimerate",
            name="irrigation_method",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.irrigationmethod",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="irrigationtimerate",
            name="soil_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.soiltype",
            ),
            preserve_default=False,
        ),
    ]
