# Generated by Django 4.2.3 on 2023-07-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0011_remove_irrigationtimerate_irrigation_method_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="farmerpumprelation",
            table="farmer_pumps",
        ),
    ]
