# Generated by Django 4.2.3 on 2023-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0012_alter_farmerpumprelation_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="gat_number",
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="phone_number",
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="name_mr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="name_mr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="irrigationmethod",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="irrigationmethod",
            name="name_mr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="soiltype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="soiltype",
            name="name_mr",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
